# Generated by Django 6.0.1 on 2026-03-10 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Taquería Los Compadres', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dias_de_venta', models.CharField(blank=True, help_text='Ej. Fines de semana', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True, help_text='Desmarcar si el negocio cierra temporalmente')),
                ('administrador', models.ForeignKey(limit_choices_to={'perfil__rol': 'Administrador'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_administrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Pizza de Pepperoni', max_length=100)),
                ('variante', models.CharField(blank=True, help_text='Ej. Familiar, Individual', max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(help_text='Ej. Cajas de Pizza, Harina, Queso', max_length=100)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(help_text='Ej. Kg, Litros, Piezas', max_length=20)),
                ('stock_minimo', models.DecimalField(decimal_places=2, help_text='El sistema avisará cuando la cantidad actual baje de este número', max_digits=10)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='proyectos.proyecto')),
            ],
        ),
    ]
