# Generated by Django 6.0.1 on 2026-02-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_laura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
