# Generated by Django 6.0.1 on 2026-03-10 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado')], default='Empleado', max_length=20, verbose_name='Rol')),
                ('puesto', models.CharField(blank=True, choices=[('Chef / Cocinero', 'Chef / Cocinero'), ('Cajero', 'Cajero'), ('Mesero', 'Mesero'), ('Barista', 'Barista'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Puesto')),
                ('puesto_personalizado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto Específico')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='proyectos.proyecto', verbose_name='Proyecto Asignado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
