# Generated by Django 6.0.1 on 2026-03-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Pedidos',
            field=models.ManyToManyField(blank=True, related_name='clientes_pedidos', to='clientes.pedido'),
        ),
    ]
