# Generated by Django 6.0.1 on 2026-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente 🔴'), ('ATENDIENDO', 'Atendiendo 🟡'), ('LIBERADO', 'Liberado 🟢'), ('CANCELADO', 'Cancelado ⚫')], default='PENDIENTE', max_length=20),
        ),
    ]
