# Generated by Django 6.0.1 on 2026-04-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombre_invitado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre (Cliente de paso)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.cliente'),
        ),
    ]
